/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Library {
    public static void main(String[] args) {
        System.out.println("hello world"); 
    }
}
